name: Deploy Secret Share

on:
  push:
    branch: [develop]

jobs:
  deploy-to-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SFTP DEPLOY
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: "program.cs"
          target: "/home/freshfish/"
