name: Deploy Secret Share
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SFTP DEPLOY
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.PRIVATE_KEY }}
          username: ${{secrets.USERNAME}}
          port: ${{ secrets.PORT }}
          source: "Program.cs"
          target: "/home/${{secrets.USERNAME}}"
